# Generated by Django 5.2 on 2025-04-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('user_name', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('user_email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.useraccount')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.useraccount')),
                ('dr_name', models.CharField(max_length=30)),
                ('dr_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('dr_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('facility_addr', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.useraccount')),
                ('patient_name', models.CharField(max_length=30)),
                ('diagnosis', models.CharField(max_length=225)),
                ('treatment_notes', models.CharField(max_length=225)),
                ('prescription', models.CharField(max_length=225)),
                ('blood_type', models.CharField(max_length=30)),
                ('notes', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('appt_type', models.CharField(blank=True, max_length=30, null=True)),
                ('facility_addr', models.CharField(blank=True, max_length=30, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.record')),
            ],
            options={
                'unique_together': {('patient', 'doctor', 'date', 'time')},
            },
        ),
    ]
