# Generated by Django 5.2 on 2025-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_record_patient_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='checkup', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='facility',
            field=models.CharField(default='mtsu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
