# Generated by Django 5.2 on 2025-04-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='Checkup', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='facility',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
