# Generated by Django 5.2 on 2025-04-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_message_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date', '-time']},
        ),
    ]
