# Generated by Django 5.2 on 2025-04-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date', 'time']},
        ),
    ]
