# Generated by Django 5.2 on 2025-04-03 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='patient',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dr_email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dr_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dr_phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='facility_addr',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_id',
            field=models.CharField(default=12, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'doctor', 'date_time')},
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appt_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='facility_addr',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
