# Generated by Django 5.2 on 2025-04-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_appointment_type_appointment_facility_and_more'),
        ('core', '0004_appointment_appointment_type_appointment_facility'),
    ]

    operations = [
    ]
