# Generated by Django 5.2 on 2025-04-12 21:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250412_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='Checkup', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='facility',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(default='Flu', max_length=100)),
                ('test_result', models.CharField(default='Negative', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
